_target_: src.models.mich.MICH

L: 3
C: 32
c_enc: 32
c_dec: 32
num_freqs: 12
min_freq: 5.0
max_freq: 32.0
tcn_kernel: 3
spatial_radius: 5
grid_size: 32

embed_dim: 24 # This needs to be manually set. 2 x num_freqs
out_channels: 21

heinzle_net:
  _target_: src.models.blocks.HeinzleNet

  layer_mixing_config:
    L: ${model.L}
    C: ${model.C}
    init_identity: true

  spatial_encoder_config:
    - cin: ${model.C}
      cout: ${model.c_enc}
      stride: 1
      dw_kernel: 3
      pw_kernel: 1
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      cout: ${model.c_enc}
      stride: 1
      dw_kernel: 3
      pw_kernel: 1
      num_groups: 8
      activation: silu

  temporal_mixing_config:
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu

  time_embedding_config:
    num_freqs: ${model.num_freqs}
    min_freq: ${model.min_freq}
    max_freq: ${model.max_freq}

  time_film_config:
    embed_dim: ${model.embed_dim}
    hidden_dim: ${model.c_dec}
    activation: silu
    c_dec: ${model.c_dec}

  spatial_decoder_config:
    cin: ${model.c_enc}
    c_dec: ${model.c_dec}
    out_channels: ${model.out_channels}
    activation: silu
    L: ${model.L}

normaliser:
  _target_: src.models.normaliser.LayerwiseBOLDNormalizer
  H: ${model.grid_size}
  W: ${model.grid_size}
  eps: 1.0e-6
  freeze_after_steps: 5000
  neighbourhood_radius: ${model.spatial_radius}

loss_config:
  lambda_data: 10.0
  lambda_physics: 0.1
  lambda_src: 10.0
  lambda_smooth: 10.0
  n_time: 80
  n_space: 900
  dense_time_frac: 0.85
  dense_time_lo: 0.1
  dense_time_hi: 0.70
  uniform_time_lo: 0.1
  dense_spatial_frac: 0.8
  dense_spatial_radius: ${model.spatial_radius}
  burn_in: 0

haemo:
  kappa: 0.65
  gamma: 0.41
  alpha: 0.32
  tau: 2.66
  lambda_d: 0.5

acquisition:
  f0: 28.625
  E0: 0.34
  TE: 0.25
  r0: 340
  eps: 1.0e-32
  k1: 10.4624375
  k2: 2.433125e-32
  k3: 1.0

V0: 0.5

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3.0e-4
  weight_decay: 1.0e-5

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 125000
  eta_min: 1.0e-6

lightning:
  interval: step
  frequency: 1
  monitor: val/total_loss
