_target_: mich.models.supervised.SupervisedMICH

L: 1
C: 32
c_enc: 64
tcn_kernel: 3
spatial_radius: 2
grid_size: 10

net:
  _target_: mich.models.blocks.FullySupervisedNet
  c_enc: ${model.c_enc}

  layer_mixing_config:
    L: ${model.L}
    C: ${model.C}
    init_identity: true

  spatial_encoder_config:
    - cin: ${model.C}
      cout: ${model.c_enc}
      stride: 1
      dw_kernel: 3
      pw_kernel: 1
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      cout: ${model.c_enc}
      stride: 1
      dw_kernel: 3
      pw_kernel: 1
      num_groups: 8
      activation: silu

  temporal_mixing_config:
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu
    - cin: ${model.c_enc}
      kernel_size: ${model.tcn_kernel}
      num_groups: 8
      activation: silu

normaliser:
  _target_: mich.models.normaliser.LayerwiseBOLDNormalizer
  H: ${model.grid_size}
  W: ${model.grid_size}
  eps: 1.0e-6
  freeze_after_steps: 5000
  neighbourhood_radius: ${model.spatial_radius}

loss_config:
  lambda_pearson: 1.0

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 3.0e-4
  weight_decay: 1.0e-5

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 125000
  eta_min: 1.0e-6

lightning:
  interval: step
  frequency: 1
  monitor: val/loss/total
