wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  entity: ${private.entity}
  offline: False
  id: null
  log_model: False
  group: ${network_name}
  project: ${project_name}
  name: "${network_name}: rank 0"
  save_dir: ${paths.full_path}
  resume: ${resume.state}
