latest_model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.full_path}/checkpoints
  every_n_train_steps: 100
  save_on_train_epoch_end: true
  filename: last

best_model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: ${paths.full_path}/checkpoints
  monitor: val/loss/total
  mode: min
  save_weights_only: false
  save_last: false
  auto_insert_metric_name: False
  filename: best

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step

model_summary:
  _target_: pytorch_lightning.callbacks.ModelSummary
  max_depth: 2
