_target_: pytorch_lightning.Trainer
min_epochs: 10
max_epochs: 500
enable_progress_bar: True
num_sanity_val_steps: 2
log_every_n_steps: 100
check_val_every_n_epoch: 20
accelerator: auto
devices: 1
strategy: auto # ddp
gradient_clip_val: 5.0
precision: bf16-mixed
enable_model_summary: False
default_root_dir: ${paths.full_path}
