# @package _global_

# Order indicates overwriting
defaults:
  - _self_
  - private: private.yaml
  - paths: default.yaml
  - trainer: default.yaml
  - model: default.yaml
  - datamodule: default.yaml
  - loggers: default.yaml
  - hydra: default.yaml
  - callbacks: default.yaml
  - experiments: null

seed: null # For reproducibility, remove it for generative models.
project_name: mich-bold-inversion # Determines output directory path and wandb project
network_name: single_layer_linearised # Used for both saving and wandb
train: True # Set False to skip model training
ckpt_path: null # Checkpoint path to resume training
print_config: False # Print the final config to the console
# Extra tweaks available with the new pytorch version
precision: medium # Should use medium if on ampere gpus
compile: False # Can set to default for faster compiles

resume:
  state: False
  ckpt_flag: "*last*"